# Generated by Django 4.1 on 2023-01-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_signup_delete_signin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password1',
        ),
    ]
